### ISSUE TITLE
Not possible to create report for current month

### ISSUE THREAD

**Issue by link-alex** [kirilknysh/ov-reporter#1]
current month is July (#7)

> ovr ... -m 7 -v

[verbose] 2018-07-23T14:15:44.255Z Start
[verbose] 2018-07-23T14:15:44.258Z Create browser
[verbose] 2018-07-23T14:15:44.453Z Create page
[verbose] 2018-07-23T14:15:44.624Z Return facade
👤   Opening your history...
[verbose] 2018-07-23T14:15:44.625Z Go to historyUrl: https://www.ov-chipkaart.nl/mijn-ov-chip/mijn-ov-reishistorie.htm
[verbose] 2018-07-23T14:15:46.416Z Login
[verbose] 2018-07-23T14:15:46.417Z Type username: name
[verbose] 2018-07-23T14:15:46.452Z Type password
[verbose] 2018-07-23T14:15:46.474Z Click login
[verbose] 2018-07-23T14:15:48.479Z Verify user menu
[verbose] 2018-07-23T14:15:48.483Z Login done
[verbose] 2018-07-23T14:15:48.483Z History open
💳   Select your card
[verbose] 2018-07-23T14:15:48.483Z Card to select: 3528013387325124
[verbose] 2018-07-23T14:15:48.490Z Card selector: .--ov-reporter-cli-card
[verbose] 2018-07-23T14:15:48.490Z Click on selected card
[verbose] 2018-07-23T14:15:48.508Z Card selected
🗓    Select month
[verbose] 2018-07-23T14:15:48.508Z Current page URL: https://www.ov-chipkaart.nl/mijn-ov-chip/mijn-ov-reishistorie.htm?mediumid=wfqSl38VvSnjE8_xQ7d6FdpdqnR4VLusHT7JturCfRQ#selected-card
[verbose] 2018-07-23T14:15:48.509Z Month to select: 7
[verbose] 2018-07-23T14:15:48.511Z Period page URL: https://www.ov-chipkaart.nl/mijn-ov-chip/mijn-ov-reishistorie.htm?mediumid=wfqSl38VvSnjE8_xQ7d6FdpdqnR4VLusHT7JturCfRQ&begindate=01-07-2018&enddate=31-07-2018#selected-card
[verbose] 2018-07-23T14:15:49.501Z Month selected
✅   Marking days...
[verbose] 2018-07-23T14:15:49.501Z Mark page
[verbose] 2018-07-23T14:15:50.321Z Mark page
[verbose] 2018-07-23T14:15:50.327Z Days marked
📂   Saving the report...
[verbose] 2018-07-23T14:15:50.327Z Click Create expenses overview
💩   No node found for selector: input#selected-card
[verbose] 2018-07-23T14:15:50.329Z Error: No node found for selector: input#selected-card
    at assert (/usr/local/lib/node_modules/ov-reporter-cli/node_modules/puppeteer/lib/helper.js:282:11)
    at Frame.click (/usr/local/lib/node_modules/ov-reporter-cli/node_modules/puppeteer/lib/FrameManager.js:590:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by kirilknysh** [comment]
Fixed!
